spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:movie24};encrypt=false;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME:sa}

spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.port=8080
management.endpoints.web.exposure.include=health,beans,mappings
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sixcinema122@gmail.com}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true


springdoc.swagger-ui.url=/v3/api-docs
logging.level.root=INFO
logging.level.com.your.package=INFO

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.org.springframework.security=DEBUG

vnpay.tmnCode=LFJKHSPE
vnpay.hashSecret=${VNPAY_HASH_SECRET:}
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/payment-success


spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

spring.web.resources.add-mappings=true
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**

server.servlet.welcome-page=index.html


server.forward-headers-strategy=FRAMEWORK

